spring:
  application:
    name: mt-little-giant-agent-web

  # 数据库配置
  datasource:
    url: jdbc:mysql://rm-7xv29oc5w125d296iyo.mysql.rds.aliyuncs.com:3306/little_giant_v1-2_dev?rewriteBatchedStatements=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: mobirit_dev
    password: Mobirit1709!
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Flyway数据库迁移配置
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: false
    clean-disabled: true

  # Spring AI配置
  ai:
    # 阿里云通义千问配置
    dashscope:
      apikey: ${DASHSCOPE_API_KEY:sk-7f3db520a32e40d2a83e7141e5ddc300}

    ollama:
      base-url: http://192.168.1.105:11434


    # OpenAI配置
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key}
      base-url: ${OPENAI_BASE_URL:https://api.openai-hk.com}
      model: gpt-3.5-turbo


  # 禁用不需要的自动配置
  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.vectorstore.chroma.ChromaVectorStoreAutoConfiguration

# Coze API配置
coze:
  api:
    # Coze API Token，建议通过环境变量设置
    token: ${COZE_API_TOKEN:pat_Xyvwhs6QK8hgxvFmKF9SYXk1rdbGjPSxAnEUwHitzJvLiMtzgmOYEd0N4p7r2TtY}
    # Coze API Base URL，根据账户区域选择
    # 中国区域: https://api.coze.cn
    # 国际区域: https://api.coze.com
    base-url: ${COZE_BASE_URL:https://api.coze.cn}
    # API调用超时时间（毫秒）
    timeout: ${COZE_TIMEOUT:1000000}

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.mt.agent.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    enable-sql-runner: true
    db-config:
      id-type: auto
      table-underline: true

# 服务器配置
server:
  port: 8585
  servlet:
    context-path: /
    session:
      timeout: 240m

# 日志配置
logging:
  level:
    root: INFO
    com.mt.agent: DEBUG
    org.springframework.ai: DEBUG
    com.baomidou.mybatisplus: DEBUG

# 禁用 Elasticsearch 健康检查
management:
  health:
    elasticsearch:
      enabled: false
