# Redis配置
spring:
  data:
    redis:
      host: 113.45.193.155
      port: 6379
      password: Mobirit1709!
      database: 0
      timeout: 3000

# Redisson配置
redisson:
  # 单节点配置
  singleServerConfig:
    # 连接地址，格式为redis://host:port
    address: redis://113.45.193.155:6379
    # 密码
    password: Mobirit1709!
    # 连接超时，单位：毫秒
    connectTimeout: 3000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 连接池大小
    connectionPoolSize: 64
    # 最小空闲连接数
    connectionMinimumIdleSize: 24
    # 重试次数
    retryAttempts: 3
    # 重试间隔，单位：毫秒
    retryInterval: 1500
