-- ----------------------------
-- Table structure for table workshops
-- ----------------------------
DROP TABLE IF EXISTS `workshops`;
CREATE TABLE `workshops` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` longtext NOT NULL COMMENT '''名称''',
  `url` longtext NOT NULL COMMENT '''大屏地址''',
  `code` longtext NOT NULL COMMENT '''编号''',
  `box_host` longtext NOT NULL COMMENT '''盒子地址''',
  `box_port` bigint NOT NULL COMMENT '''盒子端口''',
  `box_user` longtext NOT NULL COMMENT '''盒子用户名''',
  `box_password` longtext NOT NULL COMMENT '''盒子密码''',
  `online_status` bigint NOT NULL COMMENT '''在线状态 1在线,-1离线''',
  `cast_well_name` varchar(100) DEFAULT NULL COMMENT '''铸造井名称''',
  `cast_well_code` varchar(100) DEFAULT NULL COMMENT '''铸造井编号''',
  `cast_product_type` bigint DEFAULT NULL COMMENT '''铸造产品类型''',
  `cast_machine_type` bigint DEFAULT NULL COMMENT '''铸造机种类''',
  `install_date` datetime(3) DEFAULT NULL COMMENT '''安装日期''',
  `inspect_period` varchar(100) DEFAULT NULL COMMENT '''检查周期''',
  `cast_user_num` bigint DEFAULT NULL COMMENT '''铸造人员数量''',
  `immobilization_num` bigint DEFAULT NULL COMMENT '''固定式熔炼炉数量''',
  `tilting_num` bigint DEFAULT NULL COMMENT '''倾动式熔炼炉数量''',
  `per_shift_workers` bigint DEFAULT NULL COMMENT '''单班铸造人员数量''',
  `qr_code` varchar(200) DEFAULT NULL COMMENT '''二维码''',
  `safe_user_id` bigint DEFAULT NULL COMMENT '''安全负责人''',
  `safe_user_name` varchar(100) DEFAULT NULL COMMENT '''安全负责人名称''',
  `safe_user_phone` varchar(100) DEFAULT NULL COMMENT '''安全负责人电话''',
  `workshop_file` varchar(200) DEFAULT NULL COMMENT '''车间图片''',
  `security_switch` tinyint DEFAULT NULL COMMENT '''0关闭，1开启''',
  `effective` tinyint DEFAULT NULL COMMENT '''1启用，2正常停用，3计划停用，4紧急停用''',
  `real_user_count` bigint DEFAULT '0' COMMENT '''实时人数''',
  `real_temperature` decimal(10,2) DEFAULT NULL COMMENT '''实时温度''',
  `remark` varchar(500) DEFAULT NULL COMMENT '''备注''',
  `create_user` bigint NOT NULL COMMENT '''创建人''',
  `update_user` bigint NOT NULL COMMENT '''更新人''',
  `created_at` datetime(3) NOT NULL COMMENT '''创建时间''',
  `updated_at` datetime(3) NOT NULL COMMENT '''更新时间''',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '''状态 1:启用 -1:删除''',
  `cf_location` varchar(255) DEFAULT '厂里大堂' COMMENT '''厂区位置''',
  `level` bigint DEFAULT '1' COMMENT '''等级''',
  `risk_level` bigint DEFAULT '1' COMMENT '''风险等级''',
  `device_name` varchar(255) DEFAULT '厂1区域深井铸造' COMMENT '''设备名称''',
  `equip_location` varchar(255) DEFAULT '厂1' COMMENT '''设备位置''',
  `equip_factory` varchar(255) DEFAULT '西门子' COMMENT '''设备工厂''',
  `equip_area` varchar(255) DEFAULT '厂1' COMMENT '''设备区域''',
  `safe_lock_status` bigint DEFAULT '1' COMMENT '''安全联锁状态 1开启安全联锁 2关''',
  `lock_status` bigint DEFAULT '0' COMMENT '''当前联锁状态 0初始化状态 1联锁 2未联锁''',
  `iot_host` longtext NOT NULL COMMENT '''iot请求地址''',
  `plc_lock_status` bigint DEFAULT '1' COMMENT '''plc联锁状态 1开启 2关''',
  `plc_type` longtext NOT NULL COMMENT '''plc类型  1: 大华 2: 根云''',
  `lock_process_status` bigint DEFAULT '1' COMMENT '''联锁执行状态 1执行完  2执行中''',
  `external_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb3 COMMENT='车间表，车间又叫单元、或者井，说1号井、2号单元这种，都是对应name字段的值';

